site_name: elmah.io Documentation
site_description: Documentation on how to install and use elmah.io.
site_url: https://docs.elmah.io/
site_author: Thomas Ardal
theme:
    name: null
    custom_dir: "mkdocs_bs4/"
    static_templates:
    - 404.html
extra_css:
    - style.css
markdown_extensions:
    - markdown_fenced_code_tabs:
        template: "bootstrap4"
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
nav:
- Getting Started:
    - Quick start: index.md
    - Authentication: authentication.md
    - Integrations high level overview: integrations-high-level-overview.md
- ASP.NET / MVC / Web API:
    - Logging from WebForms: logging-to-elmah-io-from-elmah.md
    - Logging from ASP.NET MVC: logging-to-elmah-io-from-aspnet-mvc.md
    - Logging from Web API: logging-to-elmah-io-from-web-api.md
    - Logging from JavaScript: logging-to-elmah-io-from-javascript.md
    - Logging from a running website on IIS: logging-to-elmah-io-from-a-running-website-on-iis.md
    - Logging from a running website on Azure: logging-to-elmah-io-from-a-running-website-on-azure.md
    - Logging custom data: logging-custom-data.md
    - Logging errors programmatically: logging-errors-programmatically.md
    - Logging to multiple logs: logging-to-multiple-elmah-logs.md
    - Remove sensitive form data: remove-sensitive-form-data.md
    - Configure elmah.io manually: configure-elmah-io-manually.md
    - Configure elmah.io from code: configure-elmah-io-from-code.md
    - Logging through a HTTP proxy: logging-through-a-http-proxy.md
    - Use multiple logs for different environments: use-multiple-logs-for-different-environments.md
    - Specify API key and log ID through appSettings: specify-api-key-and-log-id-through-appsettings.md
    - ELMAH and custom errors: elmah-and-custom-errors.md
    - Logging from a custom HTTP module: logging-from-a-custom-http-module.md
    - Upgrade elmah.io from v2 to v3: upgrade-elmah-io-from-v2-to-v3.md
    - ASP.NET troubleshooting: asp-net-troubleshooting.md
- ASP.NET Core:
    - Logging from ASP.NET Core: logging-to-elmah-io-from-aspnet-core.md
    - Logging from Microsoft.Extensions.Logging: logging-to-elmah-io-from-microsoft-extensions-logging.md
    - Logging from JavaScript: logging-to-elmah-io-from-javascript.md
    - Logging from Blazor: logging-to-elmah-io-from-blazor.md
    - Using different logs per environment in ASP.NET Core: using-different-logs-per-environment-in-aspnet-core.md
    - Roslyn analyzers for elmah.io and ASP.NET Core: roslyn-analyzers-for-elmah-io-and-aspnet-core.md
    - ASP.NET Core troubleshooting: asp-net-core-troubleshooting.md
- Logging Frameworks:
    - Logging from Serilog: logging-to-elmah-io-from-serilog.md
    - Logging from log4net: logging-to-elmah-io-from-log4net.md
    - Logging from NLog: logging-to-elmah-io-from-nlog.md
    - Logging from Microsoft.Extensions.Logging: logging-to-elmah-io-from-microsoft-extensions-logging.md
    - Logging from Logary: logging-to-elmah-io-from-logary.md
    - Logging from JSNLog: logging-to-elmah-io-from-jsnlog.md
- CMS/Blogs:
    - Logging from Umbraco: logging-to-elmah-io-from-umbraco.md
    - Logging from Sitefinity: logging-to-elmah-io-from-sitefinity.md
    - Logging from BlogEngine.NET: logging-to-elmah-io-from-blogengine-net.md
    - Logging from Orchard: logging-to-elmah-io-from-orchard.md
    - Logging from Piranha CMS: logging-to-elmah-io-from-piranha-cms.md
- Logging from something else:
    - Logging from Nancy: logging-to-elmah-io-from-nancy.md
    - Logging from ServiceStack: logging-to-elmah-io-from-servicestack.md
    - Logging from WCF: logging-to-elmah-io-from-wcf.md
    - Logging from Express: logging-to-elmah-io-from-express.md
    - Logging from DevExpress (eXpressApp Framework): logging-to-elmah-io-from-devexpress.md
    - Logging from Azure WebJobs: logging-to-elmah-io-from-azure-webjobs.md
    - Logging from Azure Functions: logging-to-elmah-io-from-azure-functions.md
    - Logging from AWS Beanstalk: logging-to-elmah-io-from-aws-beanstalk.md
    - Logging from AWS Lambdas: logging-to-elmah-io-from-aws-lambdas.md
    - Logging from Google Cloud Functions: logging-to-elmah-io-from-google-cloud-functions.md
    - Logging from Entity Framework Core: logging-to-elmah-io-from-entity-framework-core.md
    - Logging from Console: logging-to-elmah-io-from-console-application.md
    - Logging from System.Diagnostics: logging-to-elmah-io-from-system-diagnostics.md
    - Logging from PowerShell: logging-to-elmah-io-from-powershell.md
    - Logging from Windows Forms: logging-to-elmah-io-from-winforms.md
    - Logging from Xamarin: logging-to-elmah-io-from-xamarin.md
- Apps and Integrations:
    - Slack: elmah-io-apps-slack.md
    - Microsoft Teams: elmah-io-apps-teams.md
    - GitHub: elmah-io-apps-github.md
    - Bitbucket: elmah-io-apps-bitbucket.md
    - Jira: elmah-io-apps-jira.md
    - Twilio: elmah-io-apps-twilio.md
    - YouTrack: elmah-io-apps-youtrack.md
    - GitLab: elmah-io-apps-gitlab.md
    - Azure Boards: elmah-io-apps-azure-boards.md
    - Trello: elmah-io-apps-trello.md
    - HipChat: elmah-io-apps-hipchat.md
    - Zapier: integrate-elmah-io-with-zapier.md
    - BotBuster: elmah-io-apps-botbuster.md
    - IP Filter: elmah-io-apps-ipfilter.md
    - Mailman: elmah-io-apps-mailman.md
    - WebClient: elmah-io-apps-webclient.md
    - Creating apps for elmah.io: creating-apps-for-elmah-io.md
- Uptime Monitoring:
    - Set up Uptime Monitoring: setup-uptime-monitoring.md
    - Missing server side information on uptime errors: missing-server-side-information-on-uptime-errors.md
    - Allowing elmah.io uptime agents: allowing-elmah-io-uptime-agents.md
- Heartbeats:
    - Set up Heartbeats: setup-heartbeats.md
    - Logging heartbeats from ASP.NET Core: logging-heartbeats-from-asp-net-core.md
    - Logging heartbeats from Azure Functions: logging-heartbeats-from-azure-functions.md
    - Logging heartbeats from PowerShell: logging-heartbeats-from-powershell.md
    - Logging heartbeats from cURL: logging-heartbeats-from-curl.md
    - Logging heartbeats from Umbraco: logging-heartbeats-from-umbraco.md
    - Logging heartbeats from Hangfire: logging-heartbeats-from-hangfire.md
    - Logging heartbeats from .NET Core Worker Services: logging-heartbeats-from-net-core-worker-services.md
    - Logging heartbeats from AWS Lambdas: logging-heartbeats-from-aws-lambdas.md
    - Heartbeats Troubleshooting: heartbeats-troubleshooting.md
- Deployment Tracking:
    - Set up Deployment Tracking: setup-deployment-tracking.md
    - Create deployments from PowerShell: create-deployments-from-powershell.md
    - Create deployments from Octopus Deploy: create-deployments-from-octopus-deploy.md
    - Create deployments from Kudu: create-deployments-from-kudu.md
    - Create deployments from Azure DevOps Pipelines: create-deployments-from-azure-devops-pipelines.md
    - Create deployments from Azure DevOps Releases: create-deployments-from-azure-devops-releases.md
    - Create deployments from GitHub Actions: create-deployments-from-github-actions.md
    - Create deployments from Umbraco Cloud: create-deployments-from-umbraco-cloud.md
    - Create deployments from Bitbucket Pipelines: create-deployments-from-bitbucket-pipelines.md
    - Create deployments from Atlassian Bamboo: create-deployments-from-atlassian-bamboo.md
- CLI:
    - CLI overview: cli-overview.md
    - Export: cli-export.md
    - Log: cli-log.md
    - Tail: cli-tail.md
    - Dataloader: cli-dataloader.md
- Everything Else:
    - Managing Organisations and Users: managing-organisations-and-users.md
    - Where is my log ID: where-is-my-log-id.md
    - Where is my API key: where-is-my-api-key.md
    - Where is my invoice / receipt: where-is-my-invoice-receipt.md
    - How to configure API key permissions: how-to-configure-api-key-permissions.md
    - How to enable two-factor login: how-to-enable-two-factor-login.md
    - How to rename a log: how-to-rename-a-log.md
    - Creating Rules to Perform Actions on Messages: creating-rules-to-perform-actions-on-messages.md
    - Query messages using full-text search: query-messages-using-full-text-search.md
    - Tips and tricks to stay below your message limit: tips-and-tricks-to-stay-below-your-message-limit.md
    - Use Extended User Details without Email as Id: use-extended-user-details-without-email-as-id.md
    - Adding version information: adding-version-information.md
    - Bot detection: bot-detection.md
    - Include filename and line number in stack traces: include-filename-and-line-number-in-stacktraces.md
    - How to correlate messages across services: how-to-correlate-messages-across-services.md
    - How prices are calculated: how-prices-are-calculated.md
    - Export data from elmah.io to JSON: export-data-from-elmah-io-to-json.md
    - Handle elmah.io downtime: handle-elmah-io-downtime.md
    - Using the elmah.io extension for Visual Studio: using-the-elmah-io-extension-for-visual-studio.md
    - Using the REST API: using-the-rest-api.md
    - Email troubleshooting: email-troubleshooting.md
    - ELMAH and elmah.io differences: elmah-and-elmah-io-differences.md
