name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.8
      - uses: actions/setup-node@v3
        with:
          node-version: 12.16.0
      - run: npm install
      - run: gulp min
      - name: Upload source map to elmah.io
        uses: elmahio/github-upload-source-map-action@v1
        with:
          apiKey: ${{ secrets.ELMAH_IO_API_KEY }}
          logId: ${{ secrets.ELMAH_IO_LOG_ID }}
          path: '/assets/js/main.min.js'
          sourceMap: './mkdocs_bs5/assets/js/main.min.js.map'
          minifiedJavaScript: './mkdocs_bs5/assets/js/main.min.js'
      - name: Remove the .map file
        run: rm ./mkdocs_bs5/assets/js/main.min.js.map
      - run: pip install mkdocs
      - run: pip install pymdown-extensions
      - run: pip install markdown-fenced-code-tabs-next
      - run: pip install markdown
      - run: pip install mkdocs-redirects
      - run: pip install jinja2
      - run: pip3 install mkdocs-git-revision-date-localized-plugin
      - name: Update mkdocs.yml - production TRUE
        run: sed -i 's/production:\ false/production:\ true/' mkdocs.yml
      - name: Update mkdocs.yml - git-revision-date-localized ENABLED
        run: sed -i 's/enabled:\ false/enabled:\ true/' mkdocs.yml
      - name: Replace BUILD_NUMBER main.html & 404.html
        run: |
          sed -i 's/BUILD_NUMBER/${{github.run_number}}/g' ./mkdocs_bs5/main.html
          sed -i 's/BUILD_NUMBER/${{github.run_number}}/g' ./mkdocs_bs5/404.html
      - run: mkdocs gh-deploy --force --clean --verbose
      - name: Create Deployment on elmah.io
        uses: elmahio/github-create-deployment-action@v1
        with:
          apiKey: ${{ secrets.ELMAH_IO_API_KEY }}
          version: ${{ github.run_number }}
          description: ${{ github.event.head_commit.message }}
          userName: ${{ github.actor }}
          logId: ${{ secrets.ELMAH_IO_LOG_ID }}

      - name: Get Added and Modified Files
        id: changed-files
        uses: jitterbit/get-changed-files@v1

      - name: Refresh files in Bugster
        if: ${{ steps.changed-files.outputs.all != '[]' }}
        run: |
          echo "Starting step"
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            if [[ "$changed_file" == *.md ]]; then
              echo "Processing $changed_file..."
              file_content=$(cat "$changed_file" | base64 -w 0)
              curl --fail-with-body -X POST \
                   -H "Content-Type: application/json" \
                   -d "{\"filePath\": \"$changed_file\", \"content\": \"$file_content\"}" \
                   ${{ secrets.FUNCTION_APP_URL }}
            fi
          done
