name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.0
      - run: npm install
      - run: gulp min
      # here we need to upload the .map file to elmah.io API
      - name: Remove the .map file
        run: rm ./mkdocs_bs4/assets/js/main.min.js.map
      - run: pip install mkdocs
      - run: pip install pymdown-extensions
      - run: pip install markdown-fenced-code-tabs
      - name: Update mkdocs.yml
        run: sed -i 's/production:\ false/production:\ true/' mkdocs.yml
      - run: mkdocs gh-deploy --force --clean --verbose
      - name: Create Deployment on elmah.io
        uses: elmahio/github-create-deployment-action@v1
        with:
          apiKey: ${{ secrets.ELMAH_IO_API_KEY }}
          version: ${{ github.run_number }}
          description: ${{ github.event.head_commit.message }}
          userName: ${{ github.actor }}
          logId: ${{ secrets.ELMAH_IO_LOG_ID }}