name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.2
      - run: pip install markdown==3.2.1 
      - run: pip install mkdocs
      - run: pip install pymdown-extensions
      - run: pip install markdown-fenced-code-tabs
      - run: mkdocs gh-deploy --force --clean --verbose
